d1/jmutube/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from rooibos.ui.views import upload_progress
from rooibos.access.views import login, logout
from views import media_main, migrate_files, media_delete, media_rename, thumbnail, upload_file


urlpatterns = patterns('',
    url(r'^$', direct_to_template, {'template': 'jmutube-home.html'}, name='jmutube-main'),

    url(r'^admin/(.*)', admin.site.root, {'SSL': True}, name='admin'),
    url(r'^mstatic/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_DIR}, name='jmutube-master-static'),

    url(r'^accounts/login/$', login, {'template_name': 'registration/jmutube-login.html', 'SSL': True}, name='jmutube-login'),
    url(r'^accounts/logout/$', logout, {'template_name': 'registration/jmutube-logout.html'}, name='jmutube-logout'),
    url(r'^accounts/media/upload/$', upload_file, name='jmutube-upload'),
    url(r'^accounts/media/upload/progress/$', upload_progress, name='jmutube-upload-progress'),
    url(r'^accounts/media/(video|audio|images|crass|presentations)/$', media_main, name='jmutube-media'),
    url(r'^accounts/media/(video|audio|images|crass|presentations)/([^/]+)/$', media_main, name='jmutube-tagged-media'),
    url(r'^accounts/media/(video|audio|images|crass|presentations)/(\d+)/([\w-]+)/delete/$', media_delete, name='jmutube-media-delete'),
    url(r'^accounts/media/(video|audio|images|crass|presentations)/(\d+)/([\w-]+)/rename/$', media_rename, name='jmutube-media-rename'),
    url(r'^accounts/media/thumb/(?P<username>\w+)/(?P<id>\d+)/(?P<name>[-\w]+)/$', thumbnail, name='jmutube-thumbnail'),
    url(r'^accounts/media/$', media_main, {'type': 'video'}, name='jmutube-media-default'),
    url(r'^accounts/media/migrate/$', migrate_files, name='jmutube-migrate-files'),
    (r'^content/', include('apps.jmutube.repository.urls')),
    (r'^accounts/crass/', include('apps.jmutube.crass.urls')),
    url(r'^options/$', direct_to_template, {'template': 'jmutube-options.html'}, name='options'),
    url(r'^accounts/relay/$', direct_to_template, {'template': 'jmutube-relay.html'}, name="jmutube-relay"),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {'packages': 'django.conf'}, name='jmutube-jsi18n'),
    (r'^impersonate/', include('impersonate.urls')),
    url(r'^help/$', direct_to_template, {'template': 'jmutube-help.html'}, name='jmutube-help'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.JMUTUBE_STATIC_FILES}, name='jmutube-static'),
    )

d1/jmutube/crass/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django import forms
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
import os
from models import Computer, Schedule, Mapping
from datetime import date, datetime, timedelta

from apps.jmutube.util import jmutube_login_required

"""
def time_choices():
    c = []
    for h in range(0, 24):
        h2 = h % 12
        if h2 == 0: h2 = 12
        for m in range(0, 60, 10):
            c += (('%02d:%02d:00' % (h, m), '%02d:%02d %s' % (h2, m, h < 12 and 'am' or 'pm')),)
    return c

def default_time(houroffset=0):
    d = datetime.now() + timedelta(0, 0, 0, 0, 0, houroffset)
    m = ((d.minute / 10 + 1) * 10) % 60
    h = m == 0 and (d.hour + 1) or d.hour
    if (h > 23): h = 0
    return '%02d:%02d:00' % (h, m)
"""
def time_choices():
    c = []
    for h in range(0, 24):
        h2 = h % 12
        if h2 == 0: h2 = 12
        for m in range(0, 6):
            c += ((h * 6 + m, '%02d:%02d %s' % (h2, m * 10, h < 12 and 'am' or 'pm')),)
    c += ((24 * 6, '12:00 am'),)
    return c

def default_time(houroffset=0):
    d = datetime.now() + timedelta(0, 0, 0, 0, 0, houroffset)
    m = ((d.minute / 10 + 1) * 10) % 60
    h = m == 0 and (d.hour + 1) or d.hour
    if (h > 23):
        h = 24
        m = 00
    return h * 6 + m / 10


def default_date():
    t = date.today()
    return t.strftime("%m/%d/%y")

class ScheduleForm(forms.ModelForm):

    date = forms.DateField(widget=forms.TextInput(attrs = {'class': 'vDateField'}))
    start = forms.ChoiceField(choices=time_choices())
    end = forms.ChoiceField(choices=time_choices())

    class Meta:
        model = Schedule
        exclude = ('user', 'start_time', 'end_time')


@jmutube_login_required
def view_schedules(request):

    if request.method == 'POST':

        delete_schedule = filter(lambda k: k.startswith('delete_schedule_'), request.POST.keys())
        if delete_schedule:
            id = int(delete_schedule[0][16:])
            Schedule.objects.filter(user__username=request.user.username, id=id).delete()
            return HttpResponseRedirect(reverse('jmutube-crass-schedules'))
        else:
            form = ScheduleForm(request.POST)
            if form.is_valid():
                schedule = form.save(commit=False)
                schedule.user = request.user
                date = form.cleaned_data['date'];
                start = int(form.cleaned_data['start'])
                end = int(form.cleaned_data['end'])
                schedule.start_time = datetime(date.year, date.month, date.day, start / 6, (start % 6) * 10)
                if (end < start):
                    date = date + timedelta(1)
                schedule.end_time = datetime(date.year, date.month, date.day, end / 6, (end % 6) * 10)
                schedule.save()
                return HttpResponseRedirect(reverse('jmutube-crass-schedules'))

    else:
        form = ScheduleForm(initial={'start': default_time(), 'end': default_time(1), 'date': default_date()})

    d = datetime.now()-timedelta(7)
    schedules = Schedule.objects.filter(user__username=request.user.username, start_time__gte=d)
    mappings = [dict(time_stamp=m.time_stamp, file=os.path.basename(m.target_file))
                for m in Mapping.objects.filter(user__username=request.user.username, time_stamp__gte=d)]

    return render_to_response("jmutube-schedules.html",
                              {'schedules': schedules,
                               'form': form,
                               'mappings': mappings,
                               },
                              context_instance = RequestContext(request))

d1/jmutube/templates/jmutube-confirm.html
{% extends "jmutube-master.html" %}

{% block content %}

<form method="post" action="" enctype="multipart/form-data">

<div>{{ message|escape }}</div>

<input type="submit" name="SubmitButton" value="Submit" />

<a href="{% url jmutube-media type %}">Cancel</a>
</form>

{% endblock %}

d1/jmutube/templates/jmutube-help.html
{% extends "jmutube-master.html" %}

{% block content %}

<h3>Help</h3>

<p>You can always contact Grover Saunders at 540-568-3572 or <a href="mailto:saundebn@jmu.edu" target="_blank">saundebn@jmu.edu</a> for questions, feedback, and help using the site. In addition, we've begun producing a series of screencasts to give you an overview of the system and its features.</p>

<p align="center">

<h3>JMUtube Video Basics</h3>

<div style="margin: 0px; padding: 0px; overflow: hidden; width: 480px; height: 400px;">
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,115,0" width="480" height="400" id="jmutube" align="middle">
<param name="movie" value="http://jmutube.cit.jmu.edu/static/player/jmutube.swf" />
<param name="allowFullScreen" value="true" />
<param name="allScriptAccess" value="sameDomain" />
<param name="quality" value="high" />
<param name="scale" value="exactfit" />
<param name="loop" value="false" />
<param name="FlashVars" value="rssfeed=http://jmutube.cit.jmu.edu/content/cit/playlist/414/rss?player=jmutube" />
<object data="http://jmutube.cit.jmu.edu/static/player/jmutube.swf" height="400" type="application/x-shockwave-flash" width="480">
<param name="movie" value="http://jmutube.cit.jmu.edu/static/player/jmutube.swf" />
<param name="allowFullScreen" value="true" />
<param name="allScriptAccess" value="sameDomain" />
<param name="quality" value="high" />
<param name="scale" value="exactfit" />
<param name="loop" value="false" />
<param name="FlashVars" value="rssfeed=http://jmutube.cit.jmu.edu/content/cit/playlist/414/rss?player=jmutube" />
</object>
</object>
</div>


</p>

{% endblock %}

d1/jmutube/templates/jmutube-home.html
{% extends "jmutube-master.html" %}

{% block content %}

<h3>Welcome to JMUtube</h3>
<p>Over on the right, you'll see the main navigation with your options. If you're a faculty or staff member at JMU, you already have an account. Just click on <a href="http://jmutube.cit.jmu.edu/accounts/media/video/">My Files</a> and you'll see any files that have been uploaded to your account, or you can start uploading your own files.</p>

<p>If you run into any trouble and find you need help, you can click on <a href="http://jmutube.cit.jmu.edu/help/">Help</a> or shoot an email to Grover Saunders at <a href="mailto:saundebn@jmu.edu">saundebn@jmu.edu</a>. Enjoy the site.</p>

<h3>YAPANF! &bull; <span>July 21st, 2009</span></h3>
<br>
<p>That's "Yet Another Post About New Features!" if you were wondering. We've added a ton of new stuff to JMUtube over the summer, so let's take a look at a few highlights</p>

<ul>

	<li><h4>CRASS Integration</h4><p>If you're using one of the CRASS recorders in Harrison Hall, you can now schedule and claim your recordings with JMUtube instead of the older streaming site. The two will run in parallel for the rest of the summer (if you schedule a recording in both, the older site gets preference). The new scheduler offers a number of small tweaks and improvements, but the the most significant change is the ability to schedule recordings retroactively. So you can make recordings on Tuesday, but then schedule the recordings three days later on Friday when you realize you forgot.</p></li>

	<li><h4>Relay Support</h4><p>Relay is a new software offering that allows you to very easily make live recordings of your classroom lectures and have them appear in JMUtube a few hours later ready to be viewed on the web. <a href="http://cit.jmu.edu" target="_blank">CIT</a> will be offering workshops on Relay in the Fall, but you can get started right now by clicking the Relay tab and downloading the recording software. You will need to email <a href="mailto:saundebn@jmu.edu">saundebn@jmu.edu</a> to get an account before you can log in and upload though.</p></li>

	<li><h4>Improved Tag Sorting</h4>While we introduced tagging back in April, the feature has been refined significantly. Now, when you click on a tag in the tag bar at the top, you'll only see tags which would further refine your selection, similar to a faceted search. We'll be posting a screencast for tagging soon that will go into more detail, but you'll likely get a good feel for it just by playing around for a bit.</li>
</ul>

<p>As always, we're interested in your feedback, so let us know if you have questions, comments, or suggestions for the future of JMUtube.</p>



<h3>Tagging, Impersonation, and Org Accounts. Oh My! &bull; <span>April 21st, 2009</span></h3>
<br>
<p>Okay, that title is a stretch, but we have indeed added three big new features to JMUTube this week.</p>
<ul>
	<li><h4>Tagging</h4><p>You can now add tags to both videos and presentations. You'll notice a new tagging bar at the top of your files list and checkboxes next to each title. Choosing a tag (or new tag) from the drop-down menu will add that tag to any files with a check next to it. You can then use these tags to filter your view, as each tag appears in the "Show Only" list. Clicking on the green underlined SMAD202 in the image below for example would show only titles with the SMAD202 tag.</p><p align="center"><img src="{% url jmutube-static 'images/screenshots/jmutube_tagging.jpg' %}" style="border:solid thin black;" width="464" height="232"/></p></li>

	<li><h4>Impersonation</h4><p>It's common for instructors to have GAs do some of the work within JMUtube, but until now the only way to handle this was to give the GA your e-ID, which you really shouldn't do. So we've added a feature that allows a user to pretend to be you within JMUtube (with your permission of course). You'll need to contact Grover Saunders at <a href="mailto:saundebn@jmu.edu">saundebn@jmu.edu</a> to connect the two accounts, but once your accounts have been configured, the other user can log into JMUtube using their account, click the new Options menu, pick your name out of the list, and start uploading and deploying content from your account.</p><p>It's worth noting that the Options page won't appear unless impersonation has been set up for your account.</p></li>

	<li><h4>Organizational Accounts</h4><p>If you're using JMUtube on behalf of your department, you may be in a situation where you're putting departmental content into a personal account. This could create problems if that responsibility moves to someone else or you move on to another position. Along with the impersonation feature comes the ability to create accounts for departments and organizations. Then, you can simply impersonate that departmental account just as you would any other user.</p></li>

</ul>

<p>We hope you find these new features useful. Please let us know if you have any trouble with them, and if there are other features you'd like to see in the future.</p>


<h3>Features Updated, Look Still Being Tweaked &bull; <span>April 20th, 2009</span></h3>
<p>The upgrade over the weekend was a success. A few visual issues with the interface remain, but new features are available. The features will get their own post later today.</p>

{% endblock %}

d1/jmutube/templates/jmutube-master.html
{% load analytics %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>

<title>JMUtube - A Service of the Center for Instructional Technology</title>


<link href="{% url jmutube-static 'css/typography.css' %}" rel="stylesheet" type="text/css" media="screen">
<link href="{% url jmutube-static 'css/layout.css' %}" rel="stylesheet" type="text/css" media="screen">
<link href="{% url jmutube-master-static 'admin/css/forms.css' %}" rel="stylesheet" type="text/css" media="screen">
<link href="{% url jmutube-static 'jquery/jquery-ui-themeroller.css' %}" rel="stylesheet" type="text/css" media="screen">
<script type="text/javascript" src="{% url jmutube-jsi18n %}"></script>
<script type="text/javascript" src="{% url jmutube-master-static 'admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% url jmutube-master-static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
<script type="text/javascript" src="{% url jmutube-master-static 'admin/js/calendar.js' %}"></script>
<script type="text/javascript" src="{% url jmutube-master-static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
<script type="text/javascript" src="{% url jmutube-static 'jquery-1.2.6.min.js' %}"></script>
<script type="text/javascript" src="{% url jmutube-static 'jquery-ui-personalized-1.5.2.min.js' %}"></script>
<script type="text/javascript" src="{% url jmutube-static 'jquery/jquery.cookie.js' %}"></script>
{% block javascript %}
{% endblock %}
</head>

<body>

	<div id="banner">

		<a href="http://jmutube.cit.jmu.edu"><h1>JMUtube</h1></a>

		<h2>Express Yourself. Or Someone Else.</h2>

	</div>



	<div id="headerNav">

		<h2><a href="/">JMUtube Home</a></h2>

		<h3><a href="http://cit.jmu.edu">A CIT@JMU Website</a></h3>

	</div>



	<div id="navigation">
		<ul>
			<li>{% if user.is_authenticated %}
                	Hello {{ user.first_name }} {{user.last_name}}
                {% else %}
                    Hello, Guest
                {% endif %}
            </li>
			<li><a href="{% url jmutube-media "video" %}">My Files</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url options %}">Options</a></li>
   			<li><a href="{% url jmutube-help %}">Help</a></li>
			<li><a href="{% url jmutube-logout %}">Sign Out</a></li>
			{% else %}
   			<li><a href="{% url jmutube-help %}">Help</a></li>
            <li><a href="{% url jmutube-media "video" %}">Sign In</a></li>
            {% endif %}
		</ul>
	</div>



<div id="main">

{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

  {% block content %}
  {% endblock %}

</div>



{% block sidebar %}

<style type="text/css">
#main {
   margin-right: 220px;
   min-width: 555px;
    }
</style>


	<div id="sidebar">

        <h4>About &bull; <span>JMUtube</span></h4>
        <p>JMUtube is for the faculty and staff of JMU to store and deliver video and presentations. You can learn more on the <a href="/help/">Help</a> page or get started by accessing <a href="{% url jmutube-media "video" %}">your files</a>.</p>
        <h4>Twitter &bull; <span>Status</span></h4>
			<div id="twitter_div">
			<ul id="twitter_update_list"></ul>
			<a href="http://twitter.com/jmutube" id="twitter-link" style="display:block;text-align:right;">See us on Twitter...</a>
</div>

    	<h4>About &bull; <span>CIT</span></h4>

		<p> JMUtube is a service of <a href="http://cit.jmu.edu" target="_blank">The Center for Instructional Technology</a> at <a href="http://www.jmu.edu" target="_blank">James Madison University</a>. You can contact the CIT by email at <a href="mailto:cit@jmu.edu">cit@jmu.edu</a>.</p>

    	<h6>Contact:</h6>
		<p><a href="mailto:saundebn@jmu.edu">Grover Saunders </a></p>

     	<h6>Last Modified: <span>4.21.2009</span></h6

     	<img src="{% url jmutube-static 'images/footer_logo_black.gif' %}" alt="JMU Logo" />
  </div>

  <script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
  <script type="text/javascript" src="http://twitter.com/statuses/user_timeline/jmutube.json?callback=twitterCallback2&amp;count=1"></script>
{% endblock %}


{% analytics %}

{% if debug %}
<div style="background-color: #ddd; font-size: smaller; padding: 5px;
        z-index: 1000; position: absolute; right: 5px; top: 10px;
        -moz-opacity: .7; opacity: .7;"><!-- STATS: Total: %(totTime).2fs <br/>Python: %(pyTime).2fs <br/>DB: %(dbTime).2fs <br/>Queries: %(queries)d --></div>
<!--
{{ sql_queries|length }} queries:
{% for q in sql_queries %}
{{ q.sql }} ({{ q.time }})
{% endfor %}
-->
{% endif %}

</body>

</html>

d1/jmutube/templates/jmutube-media.html
{% extends "jmutube-master.html" %}

{% block sidebar%}
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(window).bind("load", function() {

        $("#checkall").click(function() {
            $(".filecheck").attr("checked", this.checked);
        });

        $("#tagfiles").val("");

        $("#tagfiles").change(function() {
            $("#files").val("");
            $(".filecheck").each(function(i, c) {
                if (c.checked) $("#files").val($("#files").val() + "," + c.value);
            });
            var tag = $("#tagfiles").val();
            if ($("#tagfiles").attr("selectedIndex") == 1)
                tag = prompt("Please enter new tags for the selected files:");
            if (tag)
            {
                $("#tag").val(tag);
                $("#taggingform").submit();
            }
        });

        $("a.removetag").click(function(a,b,c) {
            var tagnode = this.parentNode;
            var id = tagnode.id.substring(4, tagnode.id.indexOf('-', 4));
            var tag = tagnode.id.substring(tagnode.id.indexOf('-', 4) + 1)

            $.ajax({ data: { id: id, tag: tag },
                dataType: "json",
                error: function(req, status, error) { alert("Could not remove tag: " + status + " " + error); },
                success: function(data, status) { $("#" + tagnode.id).remove(); },
                type: "POST",
                url: "{% url jmutube-delete-tag user.username %}"
                });
        });
    });
</script>

{% endblock %}

{% block content %}

<ul id="contentTabs">
    <li {% ifequal type "video" %}class="selectedTab"{% endifequal %}><a href="{% url jmutube-media "video" %}">Video</a></li>
    <li {% ifequal type "audio" %}class="selectedTab"{% endifequal %}><a href="{% url jmutube-media "audio" %}">Audio</a></li>
    <li {% ifequal type "presentations" %}class="selectedTab"{% endifequal %}><a href="{% url jmutube-media "presentations" %}">Presentations</a></li>
    <li id="upload"><a href="{% url jmutube-upload %}">Upload</a></li>
    <li><a href="{% url jmutube-crass-schedules %}">CRASS Agenda</a></li>
    <li><a href="{% url jmutube-relay %}">Relay</a></li>
</ul>

{% if type %}
<form id="taggingform" method="POST" action="{{ tag_url }}">
<input type="hidden" name="tag" id="tag" value="" />
<input type="hidden" name="files" id="files" value="" />

<div style="background-color: #DDDDDD; padding: 5px; margin-bottom: 10px;">


    Tag selected files:
    <select id="tagfiles" name="tagfiles">
        <option value=""></option>
        <option>New tag...</option>
        {% for tag in all_tags %}
        <option>{{ tag }}</option>
        {% endfor %}
    </select>


    Show:
        <span><a href="{% url jmutube-media type %}">All Files</a>&nbsp;&nbsp; </span>
        {% if selected_tags %}
        Selected:
        {% for tag in selected_tags %}
        <span class="tag">{{ tag }}</span>
        {% endfor %}
        {% if tags %}
        Additional tags:
        {% endif %}
        {% endif %}

    {% for tag in tags %}
        <span class="tag"><a href="{{ tag_url }}tag={{ tag|urlencode }}">{{ tag }}</a></span>
    {% endfor %}
</div>
</form>
{% endif %}

{% block mediacontent %}

{% endblock %}


{% endblock %}

d1/jmutube/templates/jmutube-options.html
{% extends "jmutube-master.html" %}

{% load impersonate_tags %}

{% block content %}

<h3>Options</h3>
<p>This options page serves as a space to add extra and interesting features to JMUtube. You can think of this sort of like the labs section in Gmail. You will only see features here than apply to you, so you may see nothing at all below. As new features are added, we'll make updates to the front page and the help section so you'll know what's available.

<div class="options_odd">
    {% impersonation_form %}
</div>
{% endblock %}


d1/jmutube/templates/jmutube-rename.html
{% extends "jmutube-master.html" %}

{% block content %}

<form method="post" action="">

{{ form }}

<input type="submit" name="SubmitButton" value="Submit" />

<a href="{% url jmutube-media type %}">Cancel</a>
</form>

{% endblock %}

d1/jmutube/templates/jmutube-schedules.html
{% extends "jmutube-master.html" %}
{% load humanize %}

{% block javascript %}
<script type="text/javascript">

var in_update_times = false;
function update_times(new_start, new_end)
{
    if (in_update_times) return; // recursive change events
    in_update_times = true;
    var drop_start = parseInt($('#id_start').val());
    var drop_end = parseInt($('#id_end').val());
    var slider_start = $('#timerange').slider('value',0);
    var slider_end = $('#timerange').slider('value',1);
    if (new_start != drop_start || new_start != slider_start)
    {
        if (new_start == 24 *6) new_start--;
        if (new_start >= new_end) new_end = new_start + 1;
        if (new_end - new_start > 18) new_end = new_start + 18;
    }
    else
    {
        if (new_end == 0) new_end++;
        if (new_start >= new_end) new_start = new_end - 1;
        if (new_end - new_start > 18) new_start = new_end - 18;
    }
    if (new_start != drop_start) $('#id_start').val(new_start);
    if (new_end != drop_end) $('#id_end').val(new_end);
    if (new_end != slider_end) $('#timerange').slider('moveTo', new_end, 1);
    if (new_start != slider_start) $('#timerange').slider('moveTo', new_start, 0);
    in_update_times = false;
}

$(window).bind("load", function() {
    $('#timerange').slider({ max: 24 * 6, stepping: 1, range: true,
                           handles: [{start: $('#id_start').val()},
                                     {start: $('#id_end').val()}],
                           change: function(e, ui) {
                            update_times($('#timerange').slider('value',0),$('#timerange').slider('value',1)); }
                           });

    var on_dropbox_change = function() { update_times(parseInt($('#id_start').val()), parseInt($('#id_end').val())) };
    $('#id_start').bind("change", on_dropbox_change);
    $('#id_end').bind("change", on_dropbox_change);
});
</script>


<style>
.ui-slider {
background-position:center center;
background-repeat:no-repeat;
height:20px;
position:relative;
width:590px;
}
.ui-slider-handle {
background-image:url({% url jmutube-static 'slider-handle.gif' %});
height:23px;
left:0;
position:absolute;
top:0;
margin-top: 5px;
width:12px;
z-index:1;
}
.ui-slider-handle-active {
border:1px dotted black;
}
.ui-slider-disabled .ui-slider-handle {
opacity:0.5;
}
.ui-slider-range {
background:#50A029 none repeat scroll 0 0;
height:100%;
opacity:0.3;
position:absolute;
width:100%;
}
.ui-slider, .ui-slider-1 {
background-image:url({% url jmutube-static 'slider-bg-1.png' %});
}
.ui-slider-2 {
background-image:url({% url jmutube-static 'slider-bg.png' %});
}

</style>


{% endblock %}


{% block content %}

<ul id="contentTabs">
    <li {% ifequal type "video" %}class="selectedTab"{% endifequal %}><a href="{% url jmutube-media "video" %}">Video</a></li>
    <li {% ifequal type "audio" %}class="selectedTab"{% endifequal %}><a href="{% url jmutube-media "audio" %}">Audio</a></li>
    <li {% ifequal type "presentations" %}class="selectedTab"{% endifequal %}><a href="{% url jmutube-media "presentations" %}">Presentations</a></li>
    <li id="upload"><a href="{% url jmutube-upload %}">Upload</a></li>
    <li class="selectedTab"><a href="{% url jmutube-crass-schedules %}">CRASS Agenda</a></li>
    <li><a href="{% url jmutube-relay %}">Relay</a></li>
</ul>


<h3>Schedule A CRASS Recording</h3>

<form method="post" action="">
<table>
    {{ form }}
</table>

<input type="hidden" name="start_time" id="start_time" value="7.1666" />
<input type="hidden" name="end_time" id="end_time" value="8.1666" />


<!-- <div id='timerange' class='ui-slider-2' style="margin: 40px;">
<div class='ui-slider-handle'></div>
<div class='ui-slider-handle' style="left: 188px;"></div>
</div>

 -->

<input type="submit" value="Submit Schedule" />
</form>


{% if not schedules %}

<div>You do not have any schedules during the past seven days or in the future</div>

{% else %}

<h3>Your current schedules:</h3>

<form method="post" action="">
<table>
    <tr>
        <th>Room</th>
        <th>Time</th>
        <th></th>
    </tr>
{% for schedule in schedules %}
    <tr>
        <td>{{ schedule.computer.building }} {{ schedule.computer.room }}</td>
        <td>{{ schedule.start_time|naturalday }} {{ schedule.start_time|time }} to {{ schedule.end_time|time }}
            ({{ schedule.end_time|timeuntil:schedule.start_time }})</td>
        <td><input type="submit" name="delete_schedule_{{ schedule.id }}" value="Delete" /></td>
    </tr>
{% endfor %}
</table>
</form>

{% endif %}



{% if not mappings %}

<div>No files have been transferred to your account in the past seven days</div>

{% else %}

<h3>Your recent mappings:</h3>

<table>
    <tr>
        <th>Timestamp</th>
        <th>File</th>
    </tr>
{% for mapping in mappings %}
    <tr>
        <td>{{ mapping.time_stamp|naturalday }} {{ mapping.time_stamp|time }}</td>
        <td>{{ mapping.file }}</td>
    </tr>
{% endfor %}
</table>



{% endif %}

<p><strong>Tip: You can schedule recordings in the past to claim your unscheduled recordings.</strong></p>

{% endblock %}